#!/usr/bin/env python3
"""PlatformIO pre-build hook: builds the M4 web UI (../webui) and
embeds its gzipped output into the firmware app image as PROGMEM byte
arrays, so the ESP32 serves the real app with no LittleFS/SPIFFS
involvement at all -- see docs/m4_ui_plan.md's "Technical
architecture" section for why (LittleFS is only 128KB and shared with
config.json; the app partition has ~600KB of headroom for this).

Runs automatically on every `pio run`/Upload via platformio.ini's
`extra_scripts = pre:scripts/embed_webui.py`. Regenerates
firmware/lib/api/webui_assets_data.cpp every time -- that file is
gitignored and never hand-edited (see webui_assets.h for the stable,
hand-written interface it implements).

Degrades gracefully rather than breaking the firmware build: if
Node/npm aren't installed, or the webui/ build fails, this writes a
placeholder with zero embedded assets and prints a loud warning,
instead of failing PlatformIO's build entirely. Motion/REST/WebSocket/
OTA all work fine with no web UI embedded -- this is additive, not
load-bearing for the rest of the firmware. This has NOT been run
end-to-end in the environment that wrote it (no Node/npm available
there) -- treat the whole pipeline as unverified until it's actually
been exercised once on real hardware.
"""

import gzip
import mimetypes
import os
import re
import shutil
import subprocess
import sys

Import("env")  # noqa: F821 -- injected by PlatformIO's SCons environment

# NOT __file__ -- PlatformIO/SCons runs extra_scripts via exec() against
# a shared globals dict (see SCons's SConscript.py), which never sets
# __file__ the way a normally-imported Python module would. Confirmed
# on Josh's real first build: `NameError: name '__file__' is not
# defined`. env["PROJECT_DIR"] is the documented, correct way to get an
# absolute path in a PlatformIO extra_script -- it's the directory
# platformio.ini lives in, i.e. firmware/.
FIRMWARE_DIR = env["PROJECT_DIR"]  # noqa: F821
REPO_ROOT = os.path.dirname(FIRMWARE_DIR)
WEBUI_DIR = os.path.join(REPO_ROOT, "webui")
DIST_DIR = os.path.join(WEBUI_DIR, "dist")
OUT_CPP = os.path.join(FIRMWARE_DIR, "lib", "api", "webui_assets_data.cpp")

# Explicit allowlist rather than mimetypes.guess_type() alone -- keeps
# this deterministic across OSes/Python versions rather than depending
# on whatever mimetypes db happens to be installed.
MIME_BY_EXT = {
    ".html": "text/html",
    ".js": "application/javascript",
    ".mjs": "application/javascript",
    ".css": "text/css",
    ".json": "application/json",
    ".svg": "image/svg+xml",
    ".ico": "image/x-icon",
    ".png": "image/png",
    ".woff2": "font/woff2",
}


def log(msg: str) -> None:
    print(f"[embed_webui] {msg}")


def sanitize_c_identifier(path: str) -> str:
    return "asset_" + re.sub(r"[^A-Za-z0-9_]", "_", path.strip("/"))


def write_placeholder(reason: str) -> None:
    log(f"WARNING: {reason} -- building firmware with NO embedded web UI.")
    log("Motion/REST/WebSocket/OTA are unaffected; only the web UI is missing.")
    os.makedirs(os.path.dirname(OUT_CPP), exist_ok=True)
    with open(OUT_CPP, "w") as f:
        f.write(
            "// AUTO-GENERATED by firmware/scripts/embed_webui.py -- do not edit.\n"
            f"// Placeholder: {reason}\n"
            '#include "webui_assets.h"\n\n'
            "namespace glide {\n\n"
            "const WebuiAsset kWebuiAssets[] = {};\n"
            "const size_t kWebuiAssetCount = 0;\n\n"
            "}  // namespace glide\n"
        )


def have_tool(name: str) -> bool:
    return shutil.which(name) is not None


def build_webui() -> bool:
    if not (have_tool("node") and have_tool("npm")):
        write_placeholder("Node.js/npm not found on PATH")
        return False

    node_modules = os.path.join(WEBUI_DIR, "node_modules")
    try:
        if not os.path.isdir(node_modules):
            log("Installing webui/ dependencies (npm install)...")
            subprocess.run(["npm", "install"], cwd=WEBUI_DIR, check=True)
        log("Building webui/ (npm run build)...")
        subprocess.run(["npm", "run", "build"], cwd=WEBUI_DIR, check=True)
    except subprocess.CalledProcessError as e:
        write_placeholder(f"webui/ build failed ({e})")
        return False

    if not os.path.isdir(DIST_DIR):
        write_placeholder("webui/dist/ missing after a reported-successful build")
        return False
    return True


def generate_embedded_cpp() -> None:
    entries = []
    array_defs = []
    total_gzipped = 0

    for root, _dirs, files in os.walk(DIST_DIR):
        for filename in sorted(files):
            abs_path = os.path.join(root, filename)
            rel_path = "/" + os.path.relpath(abs_path, DIST_DIR).replace(os.sep, "/")
            ext = os.path.splitext(filename)[1].lower()
            mime = MIME_BY_EXT.get(ext, "application/octet-stream")

            with open(abs_path, "rb") as f:
                raw = f.read()
            compressed = gzip.compress(raw, compresslevel=9)
            total_gzipped += len(compressed)

            ident = sanitize_c_identifier(rel_path)
            hex_bytes = ",".join(f"0x{b:02x}" for b in compressed)
            array_defs.append(
                f"static const uint8_t {ident}[] PROGMEM = {{{hex_bytes}}};"
            )
            entries.append((rel_path, ident, len(compressed), mime))

    if not entries:
        write_placeholder("webui/dist/ was empty (did `npm run build` produce output?)")
        return

    lines = [
        "// AUTO-GENERATED by firmware/scripts/embed_webui.py -- do not edit.",
        "// Regenerated on every PlatformIO build from webui/dist/.",
        '#include "webui_assets.h"',
        # PROGMEM is defined in pgmspace.h (pulled into most sketches
        # transitively via Arduino.h, but this generated file has no
        # other reason to include Arduino.h itself) -- without this,
        # every array below fails with "expected initializer before
        # 'PROGMEM'". This only surfaces once real assets exist to
        # embed: the empty placeholder (webui/dist/ missing, Node not
        # found, etc.) has zero PROGMEM arrays and compiles fine
        # either way, which is exactly how this stayed hidden until
        # the first build with Node.js actually installed.
        "#include <pgmspace.h>",
        "",
        "namespace glide {",
        "",
        *array_defs,
        "",
        "const WebuiAsset kWebuiAssets[] = {",
    ]
    for rel_path, ident, length, mime in entries:
        # "/index.html" is also served for the bare "/" request --
        # see the SPA-fallback handling in main.cpp's setupApiRoutes(),
        # which doesn't need a duplicate table entry for that.
        lines.append(f'    {{"{rel_path}", {ident}, {length}, "{mime}"}},')
    lines += [
        "};",
        f"const size_t kWebuiAssetCount = {len(entries)};",
        "",
        "}  // namespace glide",
        "",
    ]

    os.makedirs(os.path.dirname(OUT_CPP), exist_ok=True)
    with open(OUT_CPP, "w") as f:
        f.write("\n".join(lines))

    total_kb = total_gzipped / 1024
    log(f"Embedded {len(entries)} file(s), {total_kb:.1f} KB gzipped total.")
    if total_gzipped > 400 * 1024:
        log(
            f"WARNING: {total_kb:.1f} KB exceeds the ~400KB soft target "
            "(docs/m4_ui_plan.md) for real margin against firmware growth -- "
            "still under the ~598KB hard budget, but worth a look."
        )


if build_webui():
    generate_embedded_cpp()

sys.stdout.flush()
